- alias: Living Room Lights (On)
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_unknown_type0004_id0001_sensor_3_0
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: group.livingroom_lights
